config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
#   resources :post
  root to: "pages#home"
  get '/about', to: 'pages#about'
  get '/general_information', to: 'pages#general_information'
  get '/taxonomy_overview', to: 'pages#taxonomy_overview'

  

  resources :directory, only: [:index, :show] do 
    resources :species, only: [:show]
  end
  
  resources :species, only: [:index]
  
  
  # Redirects users who enter a wrong route path.  Will disable while in development...
  # match '*path' => redirect('/'), via: :get

  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/family.rb
class Family < ActiveRecord::Base
  belongs_to :kingdom
  belongs_to :phylum  
  belongs_to :fossil_class
  belongs_to :order
  has_many :generas
  has_many :fossils
  
  # In order for active admin to recognize the display name/label...
  def display_name
    family_name
  end    

end

app/models/fossil.rb
class Fossil < ActiveRecord::Base
  belongs_to :kingdom
  belongs_to :phylum
  belongs_to :fossil_class
  belongs_to :order
  belongs_to :family
  belongs_to :genera
  
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "fossil-default.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/  
  
    # In order for active admin to recognize the display name/label...
  def display_name
    species_name
  end  
  
  
  
  validates :species_name, presence: true
  validates :kingdom_id, :phylum_id, :fossil_class_id, :order_id, :family_id, :genera_id, presence: { message: "must be given please" }
  
  
end

app/models/fossil_class.rb
class FossilClass < ActiveRecord::Base
  belongs_to :kingdom       
  belongs_to :phylum
  has_many :fossils
  has_many :orders
  has_many :families
  has_many :generas
  
    # In order for active admin to recognize the display name/label...
  def display_name
    class_name
  end  
end

app/models/genera.rb
class Genera < ActiveRecord::Base
  belongs_to :kingdom
  belongs_to :phylum  
  belongs_to :fossil_class
  belongs_to :order
  belongs_to :family
  has_many :fossils
  
  
  # In order for active admin to recognize the display name/label...
  def display_name
    genus_name
  end    

end

app/models/kingdom.rb
class Kingdom < ActiveRecord::Base
  has_many :fossils
  has_many :phylums
  has_many :fossil_classes
  has_many :orders
  has_many :families
  has_many :generas
  
  # In order for active admin to recognize the display name/label...
  def display_name
    kingdom_name
  end  

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :kingdom
  belongs_to :phylum  
  belongs_to :fossil_class       
  has_many :families
  has_many :fossils
  has_many :generas
  
  # In order for active admin to recognize the display name/label...
  def display_name
    order_name
  end    

end

app/models/phylum.rb
class Phylum < ActiveRecord::Base
  belongs_to :kingdom       
  has_many :fossils
  has_many :fossil_classes
  has_many :orders
  has_many :families
  has_many :generas
  
    # In order for active admin to recognize the display name/label...
  def display_name
    phylum_name
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/directory_controller.rb
class DirectoryController < ApplicationController

  add_breadcrumb "Home", :root_path 
  add_breadcrumb "Main Directory", :directory_index_path



  def index
    
    @phylums = Phylum.all
    @classes = FossilClass.all
    # In case the id of the Kingdom changes on a future db update, I loop for the
    # appropiate kingdom by name and invoke the id in the view file.
    @animalia = Kingdom.find_by kingdom_name: 'Animalia'
    @protozoa = Kingdom.find_by kingdom_name: 'Protozoa'
  end
  
  def show
    
    add_breadcrumb "Sub Directory" 

    
    @q = Fossil.ransack(params[:q])
    @fossil_s = @q.result.includes(:kingdom, :phylum, :fossil_class, :order, :family, :genera)
    
    # Phylum param assigned from the index file to url route.  Phylum.id
    @phylum_id = params[:id]
    # Finds the phylum record that matches the id param forwarded from the index. 
    @phylum_find = Phylum.find_by id: @phylum_id
    # These are all the fossils that share the phylum_id with the index parameter.
    @fossils = @fossil_s.where phylum_id: @phylum_id
    # Redirects if the expected Phylum.id param is not found in the db...
    redirect_to directory_index_path if @phylum_find.nil?
    
    # IF there is a class_var query string...
    if params[:class_var]
      # Query string instance var...
      @class_var = params[:class_var]
      # Find the class record whose name matches the query string
      @class = FossilClass.find_by class_name: @class_var 
      # Of the expected FossilClass.class_name query string is not found in the db...
      redirect_to directory_index_path if @class.nil?
    end
    
    
  end
  
  
end
  

app/controllers/fossils_controller.rb
class FossilsController < ApplicationController
  def new
      @fossil = Fossil.new
  end
  
  def create
    @fossil = Fossil.new(fossil_params)
    if @fossil.save
        flash[:success] = "Profile Updated"
        redirect_to root_path
    else
        render action: :new
    end    
  end
  
  
  
  private
  
  def fossil_params
      paras_allow = :kingdom_id, :phylum_id, :fossil_class_id, :order_id, :family_id, :genera_id, :summary, :remarks, :species_name, :env_int, :author, :age_range, :avatar
      params.require(:fossil).permit(paras_allow)
  end  
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    add_breadcrumb "Home", :root_path
  end
  
  def about
    add_breadcrumb "Home", :root_path
    add_breadcrumb "About"
  end
  
  def general_information
  add_breadcrumb "Home", :root_path
  add_breadcrumb "General Information"
  end
  
  def taxonomy_overview
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Taxonomy Overview"  
  end
  
  
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  
  def show
  
  add_breadcrumb "Home", :root_path 
  add_breadcrumb "Main Directory", :directory_index_path
  add_breadcrumb "Details" 
  
  @fossil = Fossil.find(params[:id])

  rescue ActiveRecord::RecordNotFound
    redirect_to directory_index_path, :flash => { :error => "Record not found." }

  end
  
  
  def index
    
  add_breadcrumb "Home", :root_path 
  add_breadcrumb "Main Directory", :directory_index_path    
  add_breadcrumb "All Species" 
    
    @q = Fossil.ransack(params[:q])
    @fossils = @q.result.includes(:kingdom, :phylum, :fossil_class, :order, :family, :genera)    
    # @fossils = Fossil.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/dramas_helper.rb
module DramasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/directory/index.html.erb
<div class="index-header">
  <div class= "container">
    <div class = "row">
      <div class = "col-md-12">
      
      <h2 class= 'show-title text-center'> <strong>Main Directory</strong> </h2>
      
        <div class='col-md-12'>  
          <div class="panel panel-default">
            <div class="panel-heading text-center"><h4 class='text-center'>Kingdom: Animalia</h4></div>
            <div class="panel-body">
              <div class='a-well'>
                <% @phylums.each do |x| %>
                <!-- If the phylum records have the dynamic id of Animalia...-->
                  <% if x.kingdom_id == @animalia.id %>
                    <!--Link to a show page where all the species share the same phylum_id -->
                    <%= link_to directory_path(x.id) do %>
                      <h5>Phylum: <strong><%= x.phylum_name %></strong></h5>
                    <% end %>  
                    <ul  style="list-style: none;">
                      <% @classes.each do |z| %>
                      <!-- Here, we do the same as above except we attach a dynamic query string-->
                      <!-- to filter the classes in the show view file... -->
                        <%= link_to directory_path(x.id, class_var: "#{z.class_name}") do %>
                          <% if z.phylum_id == x.id %>
                            <li> <h5><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                             Class: <%= z.class_name %> </h5> </li>
                          <% end %>
                        <% end %>  
                      <% end %>
                    </ul>
                    </br>
                  <% end %>
                <% end %> <!-- end for each loop -->
              </div>  <!-- body foreground div -->
            </div> <!--panel body end-->
          </div> <!-- panel scaffold end-->
        </div> <!-- new container -->
        
        <div class = 'col-md-12'>
          <div class="panel panel-default">
            <div class="panel-heading"><h4 class='text-center'> Kingdom: Protozoa </h4></div>
            <div class="panel-body">
              <div class='a-well'>
                <% @phylums.each do |x| %>
                <!-- If the phylum records have the dynamic id of Protozoa...-->
                  <% if x.kingdom_id == @protozoa.id %>
                    <%= link_to directory_path(x.id) do %>
                      <h5> Phylum: <strong><%= x.phylum_name %></strong></h5>
                    <% end %>  
                    
                    <ul  style="list-style: none;">
                      <% @classes.each do |z| %>
                      <!-- Here, we do the same as above except we attach a dynamic query string-->
                      <!-- to filter the classes in the show view file... -->              
                        <%= link_to directory_path(x.id, class_var: "#{z.class_name}") do %>
                          <% if z.phylum_id == x.id %>
                            <li> <h5><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                            Class: <%= z.class_name %> </h5> </li>
                          <% end %>  
                        <% end %>
                      <% end %>
                    </ul>
                  <% end %>
                <% end %> <!-- end for each loop--> 
              </div> <!-- a-well end -->  
            </div><!--panel body end-->
          </div> <!-- panel scaffold end-->
        </div> <!--new col end-->  
      
      </div>
    </div> <!-- full col end -->
  </div>
</div>

app/views/directory/show.html.erb
<div class="index-header">
  <div class= "container">
    <div class = "row">
      <div class = "col-md-12">
        
        <h2 class= 'show-title text-center'> <strong> Sub Directory </strong></h2>
        
        <!-- Sorting Links -->
        <div class ='row'>
          <div class='col-md-2'>
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Sort by:
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                <li>            
                  <%= sort_link(@q, :species_name) do %>
                    Species Name
                  <% end %>   
                </li>
                <li>
                  <%= sort_link(@q, :phylum_phylum_name) do %>
                    Phylum
                  <% end %>      
                </li>      
                <li>
                  <%= sort_link(@q, :fossil_class_class_name) do %>
                    Class
                  <% end %>      
                </li>      
                <li>
                  <%= sort_link(@q, :order_order_name) do %>
                    Order
                  <% end %>      
                </li> 
                <li>
                  <%= sort_link(@q, :family_family_name) do %>
                    Family
                  <% end %>      
                </li> 
                <li>
                  <%= sort_link(@q, :genera_genus_name) do %>
                    Genus
                  <% end %>      
                </li>            
              </ul>
            </div> <!-- dropdown-->
          </div> <!-- col -->
          
          <div class="col-sm-4 col-md-offset-6 col-md-4">
            <%= search_form_for @q, url: directory_path do |f| %>
              <div class="input-group">
                <span class="input-group-btn">
                  <%= f.submit 'Go!', class: 'btn btn-default' %>
                </span>
                  <%= f.text_field :species_name_or_kingdom_kingdom_name_or_phylum_phylum_name_or_fossil_class_class_name_or_family_family_name_or_genera_genus_name_cont ,placeholder: "Search field", class: 'form-control' %>
              </div><!-- /input-group -->
            <% end %>
          </div> <!-- col -->
                
        </div> <!-- row -->        
        

      <div class="panel panel-default">
        <div class="panel-heading">
          <% if params[:class_var].blank? %>
            <h4 class= 'text-center'> All available species of the <%= @phylum_find.phylum_name %> phylum </h4>
          <% else %>
            <h4 class = 'text-center'> All available species of the <%= @phylum_find.phylum_name %> phylum <i class="fa fa-angle-double-right" aria-hidden="true"></i> <%= @class.class_name %> class. </h4>
          <% end %>
        </div> <!-- panel heading end -->
        
        <div class="panel-body">
          <% @fossils.each do |x| %>
            <%if params[:class_var] && x.fossil_class_id == @class.id %>
              <div class='a-well'>
                <%= link_to directory_species_path(@phylum_id, x.id) do %>
                  <h4><strong><%= x.species_name %></strong></h4>
                <% end %>
                <div class = 'description'>
                  <ul><h5>| Kingdom: <small><%= x.kingdom.kingdom_name %></small></h5> <h5>| Phylum: <small><%= x.phylum.phylum_name%></small></h5> <h5>| Class: <small><%= x.fossil_class.class_name %></small></h5> <h5>| Order: <small><%= x.order.order_name %></small></h5> <h5>| Family: <small><%= x.family.family_name %></small></h5><h5> | Genus: <small><%= x.genera.genus_name %></small></h5></ul> </br>
                </div>
              </div> <!-- well end -->
            <% elsif params[:class_var].blank? %>
              <div class='a-well'>  
                <%= link_to directory_species_path(@phylum_id, x.id) do %>
                  <h4><strong><%= x.species_name %></strong></h4>
                <% end %>
                <div class = 'description'>
                  <ul><h5>| Kingdom: <small><%= x.kingdom.kingdom_name %></small></h5> <h5>| Phylum: <small><%= x.phylum.phylum_name%></small></h5> <h5>| Class: <small><%= x.fossil_class.class_name %></small></h5> <h5>| Order: <small><%= x.order.order_name %></small></h5> <h5>| Family: <small><%= x.family.family_name %></small></h5><h5> | Genus: <small><%= x.genera.genus_name %></small></h5></ul> </br>
                </div>
              </div> <!-- well-end -->
            <% end %>
          <% end %> <!-- main each end -->
        </div> <!-- panel body end -->
      </div>  <!-- panel end -->  
        
      </div>
    </div>
  </div>
</div>

app/views/fossils/new.html.erb
<h1> Form for creating a new post!</h1>
<!--multipart is for file upload! -->
<%= form_for @fossil, url: fossils_path, :html => { :multipart => true } do |f| %>

  <div class = "form-group">
    <%= f.label :species_name %>
    <%= f.text_field :species_name, class: 'form-control' %>
  </div>
  
  <div class = "form-group">
    <%= f.label :kingdom_id %>
    <%= f.collection_select(:kingdom_id, Kingdom.order(:kingdom_name), :id, :kingdom_name, include_blank: true) %>    
  </div> 
  
  <div class = "form-group">
    <%= f.label :phylum_id %>
    <%= f.grouped_collection_select(:phylum_id, Kingdom.order(:kingdom_name), :phylums, :kingdom_name, :id, :phylum_name) %>    
  </div>
      
  <div class = "form-group">
    <%= f.label :fossil_class_id %>
    <%= f.grouped_collection_select(:fossil_class_id, Phylum.order(:phylum_name), :fossil_classes, :phylum_name, :id, :class_name) %>    
  </div>  
  
  <div class = "form-group">
    <%= f.label :order_id %>
    <%= f.grouped_collection_select(:order_id, FossilClass.order(:class_name), :orders, :class_name, :id, :order_name) %>    
  </div> 
  
  <div class = "form-group">
    <%= f.label :family_id %>
    <%= f.grouped_collection_select(:family_id, Order.order(:order_name), :families, :order_name, :id, :family_name) %>    
  </div>        

  <div class = "form-group">
    <%= f.label :genera_id %>
    <%= f.grouped_collection_select(:genera_id, Family.order(:family_name), :generas, :family_name, :id, :genus_name) %>    
  </div>
  
  <div class = "form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: "form-control" %>
  </div>    
  
  <div class = "form-group">
    <%= f.label :age_range %>
    <%= f.text_area :age_range, class: "form-control" %>
  </div>  
  
  <div class = "form-group">
    <%= f.label :author %>
    <%= f.text_area :author, class: "form-control" %>
  </div>  
  
  <div class = "form-group">
    <%= f.label :remarks %>
    <%= f.text_area :remarks, class: "form-control" %>
  </div>
  
  <div class = "form-group">
    <%= f.label :env_int %>
    <%= f.text_area :env_int, class: "form-control" %>
  </div>    
  
  <div class = "form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %> 
  </div>
  
  <div class = "form-group">
    <%= f.submit "Add new Fossil", class: 'btn btn-primary' %>
  </div>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marine Species Fossil Database</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2, user-scalable=yes">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'  %>
    <link href="https://fonts.googleapis.com/css?family=Inknut+Antiqua|Roboto" rel="stylesheet">  
    <%= csrf_meta_tags %>    
  </head>

  <body>

  <div id="wrapper" class="active">  
    
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
      <ul id="sidebar_menu" class="sidebar-nav">
         <li class="sidebar-brand"><a id="menu-toggle" href="#">Menu<span id="main_icon" class="glyphicon glyphicon-align-justify"></span></a></li>
      </ul>
      
      <ul class="sidebar-nav " id="sidebar">
  
        <li>
          <%= link_to root_path do %>
            Home
          <% end %> 
        </li>
        
        <li>
          <%= link_to general_information_path do %>
          <div class= 'multi-line-a'>
            <p>General</p> <p>Information</p>
          </div>  
          <% end %> 
        </li>
        
        <li>
          <%= link_to taxonomy_overview_path do %>
          <div class= 'multi-line-a'>
            <p>Taxonomy</p> <p>Overview</p>
          </div>  
          <% end %> 
        </li>        
        
        <li>
          <%= link_to directory_index_path do %>
            Main Directory
          <% end %> 
        </li> 
        
        <li>
          <%= link_to species_index_path do %>
            All Species
          <% end %> 
        </li>       
        
        <li>
          <%= link_to about_path do %>
            About
          <% end %> 
        </li>       
         
      </ul> <!-- sidebar-nav -->
    </div> <!-- sidebar wrapper -->
        
    <!-- Page content -->
    <div id="page-content-wrapper">
      <!-- Keep all page content within the page-content inset div! -->
      <div class="page-content inset">
        
        <div class= "container">
          <div class = "row">
            <div class='col-md-6'>
              <ol class="breadcrumb">
                <%= render_breadcrumbs :tag => :li, :separator => "" %>
                <%= notice %>
                <%= alert %>
              </ol>
            </div>
          </div> <!-- row -->
        </div> <!-- container--> 
        
      <%= yield %>
 
      </div>  <!--page inset -->
    </div> <!-- page-content-wrapper-->
    
  </div> <!-- wrapper close -->

  </body>

</html>

app/views/pages/about.html.erb
<div class="index-header">
  <div class= "container">
    <div class = "row">
      <div class = "col-md-12">
          
          
        <h2 class= 'text-center show-title'><strong>About </strong> </h2>
        
          
        <div class="panel panel-default">
          <div class="panel-heading text-center"><h4 class='text-center'> Site information and references </h4></div>
            <div class="panel-body">   
              <div class ='a-well'>
                <h4><strong> Marine Species Fossil Database </strong></h4>
                <p> The purpose of this website is to serve as an introductory paleontology application, where a user can obtain brief information about some of the major groups of marine phyla as well as a visual reference for a number of species.</p>
                <p> This application is a pet project that I've been meaning to create ever since I started learning about web development, and it's based on an undergraduate course project I did some time ago.  This website is a continuous work in progress, and it will gradually change as I slowly add, review & rectify information and/or learn new technologies that I might want to integrate.</p>
                
                </br>
                <h4><strong> References/Further Reading </strong></h4>
                <p> <i>All the information found within this piece of work originates from or has been supported with the following sources:</i></p>
                <p> Allison, P.A., and Bottjer, D.J., 2011, Taphonomy Process and Bias Through Time: Dordrecht, Springer Netherlands, v. 32. </p>
                <p> Behrensmeyer, A. K., and A. Turner. 2013. Taxonomic occurrences of Suidae recorded in the Paleobiology Database. Fossilworks. http://fossilworks.org.</p>
  				      <p> Carpenter, K. E. and Niem, H. V., 1998. The Living Marine Resources of the Western Central Pacific, Vol. 1: Seaweeds, corals, bivalves and gastropods. Rome: Food and agriculture organization of the United Nations.</p>
  				      <p> Doyle, P. 1996., Understanding fossils: An introduction to invertebrate paleontology, 1st ed, 426. New York: Wiley.</p>
  				      <p> Edwards, C.L., 1908, Biometry as a Method in Taxonomy: The American Naturalist, v. 42, p. 537-540. </p>
  				      <p> Gaines, R.R. and Droser, M.L. 2003. Ecology of the familiar trilobite Elrathia kingi: an early exaerobic zone inhabitant. California: Department of Earth Sciences, University of California.</p>
  				      <p> Mercado, S.H., Paleontology lectures & presentations. </p>
  				      <p> Moore, R.  C., et al., Treatise on Invertebrate Paleontology, Volumes A through W. Boulder, Colorado: Geological Society of America; and Lawrence, Kansas: University of Kansas Press.</p>                
                <p> Parr, C. S., N. Wilson, P. Leary, K. S. Schulz, K. Lans, L. Walley, J. A. Hammock, A. Goddard, J. Rice, M. Studer, J. T. G. Holmes, and R. J. Corrigan, Jr. 2014. The Encyclopedia of Life v2: Providing Global Access to Knowledge About Life on Earth.  Biodiversity Data Journal 2: e1079, doi:10.3897/BDJ.2.e1079</p>
                <p> Wright, R.M., and Robinson, R. 1993. Biostratigraphy of Jamaica.  Geological Society of America.</p>
                <p> WoRMS Editorial Board (2017). World Register of Marine Species. Available from http://www.marinespecies.org at VLIZ. Accessed 2017-02-28. doi:10.14284/170 </p>  				      
                </br>
                <h4><strong> Github repository </strong></h4>
                <p> https://github.com/arac-codespace/fossil_app </p>
              
              </div>
            </div>
          </div>    
        </div>    
          
        
      </div>  
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="index-header">
  <div class= "container">
    <div class = "row">
      <div class = "col-md-12">
        
        <div class = 'home-content'> 
          <div class='row home-row'>
            <div class= 'col-md-3'>
              <h1 class= 'text-center home-title'><strong>Marine Species Fossil Database</strong> </h1>
            </div>
          </div>
          
          <div class='subtitle-row row'>
            <div class='col-md-7'>  
              <p class = 'home-subtitle'>Click the [<span class='glyphicon glyphicon-menu-hamburger'></span>] icon to open the navigation bar!</p>
              <p class='home-subtitle'> Press it again to close the navigation bar! </p>
            </div>
          </div>
          
          <div class='row'>
            <div class = 'col-md-offset-0 col-md-7'>
              <div class= 'home-buttons'>
                <div class='home-btns'><%= button_to "General Information", general_information_path, :method => 'get', class: 'btn btn-primary' %></div>
                <div class='home-btns'><%= button_to "Taxonomy Overview", taxonomy_overview_path, :method => 'get', class: 'btn btn-primary' %></div>
                <div class='home-btns'><%= button_to "Main Directory", directory_index_path, :method => 'get', class: 'btn btn-primary' %></div>
                <div class='home-btns'><%= button_to "All Species", species_index_path, :method => 'get', class: 'btn btn-primary' %></div>
                <div class='home-btns'><%= button_to "About", about_path, :method => 'get', class: 'btn btn-primary' %></div>
              </div>
            </div>
          </div>
        </div> <!-- home-content end-->
        
      </div>
    </div>
  </div>
</div>

app/views/species/index.html.erb
<div class="index-header">
  <div class= "container">
    <div class = "row">
      <div class = "col-md-12">

        <h2 class= 'show-title text-center'> <strong> Sub Directory </strong></h2>
        
        <!-- Sorting Links -->
        <div class="dropdown col-sm-8 col-md-8">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Sort by:
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <li>            
              <%= sort_link(@q, :species_name) do %>
                Species Name
              <% end %>   
            </li>
            <li>
              <%= sort_link(@q, :kingdom_kingdom_name) do %>
                Kingdom
              <% end %>      
            </li>              
            <li>
              <%= sort_link(@q, :phylum_phylum_name) do %>
                Phylum
              <% end %>      
            </li>      
            <li>
              <%= sort_link(@q, :fossil_class_class_name) do %>
                Class
              <% end %>      
            </li>      
            <li>
              <%= sort_link(@q, :order_order_name) do %>
                Order
              <% end %>      
            </li> 
            <li>
              <%= sort_link(@q, :family_family_name) do %>
                Family
              <% end %>      
            </li> 
            <li>
              <%= sort_link(@q, :genera_genus_name) do %>
                Genus
              <% end %>      
            </li>            
          </ul>
        </div>         
        
        <%= search_form_for @q, url: species_index_path do |f| %>
        
          <div class="row">
            <div class="col-sm-4 col-md-4">
              <div class="input-group">
                <span class="input-group-btn">
                  <%= f.submit 'Go!', class: 'btn btn-default' %>
                </span>
                  <%= f.text_field :species_name_or_kingdom_kingdom_name_or_phylum_phylum_name_or_fossil_class_class_name_or_family_family_name_or_genera_genus_name_cont ,placeholder: "Search field", class: 'form-control' %>
              </div><!-- /input-group -->
            </div>
          </div>
            
        <% end %>        
        
        <div class="panel panel-default">
          <div class="panel-heading text-center"><h4 class='text-center'>All species available in our database </h4></div>
          <div class="panel-body">        
      
            <% @fossils.each do |x| %>
              <div class ='a-well'>
                <%= link_to directory_species_path(x.phylum_id, x.id) do%>
                  <h4><%= x.species_name %></h4>
                <% end %>  
                <div class = 'description'>
                  <ul><h5>| Kingdom: <small><%= x.kingdom.kingdom_name %></small></h5> <h5>| Phylum: <small><%= x.phylum.phylum_name%></small></h5> <h5>| Class: <small><%= x.fossil_class.class_name %></small></h5> <h5>| Order: <small><%= x.order.order_name %></small></h5> <h5>| Family: <small><%= x.family.family_name %></small></h5><h5> | Genus: <small><%= x.genera.genus_name %></small></h5></ul> </br>
                </div>                
              </div>    
            <% end %>
          </div> <!-- panel body end -->
        </div><!-- panel end -->

      </div> <!-- col end -->
    </div>
  </div>
</div>